proxy-groups:
  - name: 🚀节点选择
    type: select
    proxies: [🔯故障转移, ☑️手动切换, ♻️自动选择, ♻️自动选择all, 🇺🇸美国s, 🇪🇺欧盟s, 🇺🇳其它s, 🇺🇸美国, 🇸🇬狮城, 🇰🇷韩国, 🇯🇵日本, 🇹🇼台湾, 🇭🇰香港, 🇺🇳其它, DIRECT]
  - name: 🍃ip净化
    type: select
    include-all: true
    proxies: [🇺🇸美国s, 🇪🇺欧盟s, 🇺🇳其它s, 🚀节点选择, 🔯故障转移, ☑️手动切换, ♻️自动选择, ♻️自动选择all, 🇺🇸美国, 🇸🇬狮城, 🇰🇷韩国, 🇯🇵日本, 🇹🇼台湾, 🇭🇰香港, 🇺🇳其它]
    filter: "(?i)^(?!.*(?:香港|澳门|澳門|大陆|内地|中转|中繼|专线|專線|回国|HK|Hong Kong|Macao|Macau|CN|CHN|Back to CN)).*$"
  - name: 🔯故障转移
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 180
    proxies: [🇺🇸美国, 🇸🇬狮城, 🇰🇷韩国, 🇯🇵日本, 🇹🇼台湾, 🇭🇰香港, 🇺🇳其它]
  - name: ☑️手动切换
    proxies: [🔯故障转移, ♻️自动选择, ♻️自动选择all, 🇺🇸美国s, 🇪🇺欧盟s, 🇺🇳其它s, 🇺🇸美国, 🇸🇬狮城, 🇰🇷韩国, 🇯🇵日本, 🇹🇼台湾, 🇭🇰香港, 🇺🇳其它]
    include-all: true
    type: select
  - name: 🇺🇸美国s
    type: select
    include-all: true
    exclude-type: direct
    filter: US|USA|(?i)\b(USA?|United States)\b|美国|美國|圣何塞|聖何塞|San Jose|\bSJC\b|洛杉矶|洛杉磯|Los Angeles|\bLAX\b|硅谷|矽谷|Silicon Valley|圣克拉拉|聖克拉拉|Santa Clara|费利蒙|費利蒙|Fremont|西雅图|Seattle|\bSEA\b|拉斯维加斯|Las Vegas|凤凰城|鳳凰城|Phoenix|\bPHX\b|达拉斯|達拉斯|Dallas|\bDFW\b|芝加哥|Chicago|\bORD\b|纽约|紐約|New York|\b(NYC|JFK|EWR)\b|水牛城|Buffalo|\bBUF\b|亚特兰大|亞特蘭大|Atlanta|\bATL\b|迈阿密|Miami|\bMIA\b|华盛顿|華盛頓|Washington|\bIAD\b|俄勒冈|Oregon|\bPDX\b
  - name: 🇪🇺欧盟s
    type: select
    include-all: true
    exclude-type: direct
    filter: EU|UK|GB|DE|FR|NL|IE|SE|IT|ES|PL|FI|BE|AT|DK|CZ|LU|(?i)\b(EU|DE|Germany|Frankfurt|FRA|UK|GB|United Kingdom|London|LHR|FR|France|Paris|CDG|NL|Netherlands|Amsterdam|AMS|IE|Ireland|Dublin|DUB|SE|Sweden|IT|Italy|ES|Spain|PL|Poland|FI|Finland|BE|Belgium|AT|Austria|DK|Denmark|CZ|Czech|LU|Luxembourg)\b|欧盟|德国|德國|法兰克福|英国|英國|伦敦|法国|法國|巴黎|荷兰|荷蘭|阿姆斯特丹|爱尔兰|愛爾蘭|都柏林|瑞典|意大利|西班牙|波兰|芬兰|比利时|奥地利|丹麦|捷克|卢森堡
  - name: 🇺🇳其它s
    type: select
    include-all: true
    exclude-type: direct
    filter: ^(?i)(?!.*(CN|China|中国|大陆|HK|Hong Kong|香港|TW|Taiwan|台湾|KR|Korea|韩国|JP|Japan|日本|SG|Singapore|新加坡|US|USA|United States|美国|EU|欧盟|UK|United Kingdom|英国|GB|United Kingdom|英国|DE|Germany|德国|FR|France|法国|NL|Netherlands|荷兰|IE|Ireland|爱尔兰|SE|Sweden|瑞典|IT|Italy|意大利|ES|Spain|西班牙|PL|Poland|波兰|FI|Finland|芬兰|BE|Belgium|比利时|AT|Austria|奥地利|DK|Denmark|丹麦|CZ|Czech Republic|捷克|LU|Luxembourg|卢森堡)).*$
  - name: ♻️自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 180
    tolerance: 50
    proxies: [🇺🇸美国, 🇸🇬狮城, 🇰🇷韩国, 🇯🇵日本, 🇹🇼台湾, 🇭🇰香港, 🇺🇳其它]
  - name: ♻️自动选择all
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 180
    tolerance: 50
    include-all: true
  - name: 🤖Ai
    type: select
    proxies: [🚀节点选择, 🔯故障转移, ☑️手动切换, ♻️自动选择, ♻️自动选择all, 🍃ip净化, 🇺🇸美国s, 🇪🇺欧盟s, 🇺🇳其它s, 🇺🇸美国, 🇸🇬狮城, 🇰🇷韩国, 🇯🇵日本, 🇹🇼台湾, 🇭🇰香港, 🇺🇳其它, DIRECT]
  - name: 📺哔哩哔哩
    type: select
    proxies: [DIRECT, 🇹🇼台湾, 🇭🇰香港, 🚀节点选择, 🔯故障转移, ☑️手动切换, ♻️自动选择, ♻️自动选择all, 🍃ip净化, 🇺🇸美国s, 🇪🇺欧盟s, 🇺🇳其它s, 🇺🇸美国, 🇸🇬狮城, 🇰🇷韩国, 🇯🇵日本, 🇹🇼台湾, 🇭🇰香港, 🇺🇳其它]
  - name: 🇺🇸美国
    type: url-test
    include-all: true
    filter: US|USA|(?i)\b(USA?|United States)\b|美国|美國|圣何塞|聖何塞|San Jose|\bSJC\b|洛杉矶|洛杉磯|Los Angeles|\bLAX\b|硅谷|矽谷|Silicon Valley|圣克拉拉|聖克拉拉|Santa Clara|费利蒙|費利蒙|Fremont|西雅图|Seattle|\bSEA\b|拉斯维加斯|Las Vegas|凤凰城|鳳凰城|Phoenix|\bPHX\b|达拉斯|達拉斯|Dallas|\bDFW\b|芝加哥|Chicago|\bORD\b|纽约|紐約|New York|\b(NYC|JFK|EWR)\b|水牛城|Buffalo|\bBUF\b|亚特兰大|亞特蘭大|Atlanta|\bATL\b|迈阿密|Miami|\bMIA\b|华盛顿|華盛頓|Washington|\bIAD\b|俄勒冈|Oregon|\bPDX\b
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
  - name: 🇸🇬狮城
    type: url-test
    include-all: true
    filter: ​​SG​|SIN|(?i)\b(SG|SIN|Singapore)\b|新加坡|🇸🇬|狮城|獅城|星洲
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: 🇰🇷韩国
    type: url-test
    include-all: true
    filter: KR|(?i)\b(KR|KOR|Korea|South Korea|Republic of Korea|Seoul|ICN|Busan|Chuncheon)\b|韩国|韓國|首尔|首爾|釜山|春川
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: 🇯🇵日本
    type: url-test
    include-all: true
    filter: JP|(?i)\b(JP|JPN|Japan|Tokyo|Osaka|Saitama|NRT|HND|KIX)\b|日本|东京|東京|大阪|埼玉
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: 🇪🇺欧盟
    type: url-test
    include-all: true
    filter: EU|UK|GB|DE|FR|NL|IE|SE|IT|ES|PL|FI|BE|AT|DK|CZ|LU|(?i)\b(EU|DE|Germany|Frankfurt|FRA|UK|GB|United Kingdom|London|LHR|FR|France|Paris|CDG|NL|Netherlands|Amsterdam|AMS|IE|Ireland|Dublin|DUB|SE|Sweden|IT|Italy|ES|Spain|PL|Poland|FI|Finland|BE|Belgium|AT|Austria|DK|Denmark|CZ|Czech|LU|Luxembourg)\b|欧盟|德国|德國|法兰克福|英国|英國|伦敦|法国|法國|巴黎|荷兰|荷蘭|阿姆斯特丹|爱尔兰|愛爾蘭|都柏林|瑞典|意大利|西班牙|波兰|芬兰|比利时|奥地利|丹麦|捷克|卢森堡
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: 🇹🇼台湾
    type: url-test
    include-all: true
    filter: TW|TWN|TPE(?i)\b(Taiwan|TW|TWN|TPE|KHH|RMQ|Hinet|CHT|Taipei|Taichung|Kaohsiung)\b|台湾|台灣|臺灣|中华电信|中華電信|台北|新北|台中|彰化|高雄
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: 🇭🇰香港
    type: url-test
    include-all: true
    filter: HK|(?i)\b(HK|Hong ?Kong|HKG|HKIA|Kowloon)\b|香港|九龙|九龍|新界|中环|上环|尖沙咀|湾仔|灣仔|铜锣湾|銅鑼灣|旺角|油麻地|荃湾|沙田|大埔|屯门|元朗|西贡|东涌
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: 🇺🇳其它
    type: url-test
    include-all: true
    exclude-type: direct
    filter: ^(?i)(?!.*(CN|China|中国|大陆|HK|Hong Kong|香港|TW|Taiwan|台湾|KR|Korea|韩国|JP|Japan|日本|SG|Singapore|新加坡|US|USA|United States|美国|EU|欧盟|UK|United Kingdom|英国|GB|United Kingdom|英国|DE|Germany|德国|FR|France|法国|NL|Netherlands|荷兰|IE|Ireland|爱尔兰|SE|Sweden|瑞典|IT|Italy|意大利|ES|Spain|西班牙|PL|Poland|波兰|FI|Finland|芬兰|BE|Belgium|比利时|AT|Austria|奥地利|DK|Denmark|丹麦|CZ|Czech Republic|捷克|LU|Luxembourg|卢森堡)).*$
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
#包含欧盟(英国的全球节点)    ^(?i)(?!.*(CN|China|中国|大陆|HK|Hong Kong|香港|TW|Taiwan|台湾|KR|Korea|韩国|JP|Japan|日本|SG|Singapore|新加坡|US|USA|United States|美国)).*$

  - name: 🐟漏网之鱼
    type: select
    proxies: [🚀节点选择, 🔯故障转移, ☑️手动切换, ♻️自动选择, ♻️自动选择all, 🍃ip净化, 🇺🇸美国s, 🇪🇺欧盟s, 🇺🇳其它s, 🇺🇸美国, 🇸🇬狮城, 🇰🇷韩国, 🇯🇵日本, 🇹🇼台湾, 🇭🇰香港, 🇺🇳其它, DIRECT]
  - name: 🎯全球直连
    type: select
    proxies: [DIRECT, 🚀节点选择, 🔯故障转移, ☑️手动切换, ♻️自动选择, ♻️自动选择all, 🍃ip净化, 🇺🇸美国s, 🇪🇺欧盟s, 🇺🇳其它s, 🇺🇸美国, 🇸🇬狮城, 🇰🇷韩国, 🇯🇵日本, 🇹🇼台湾, 🇭🇰香港, 🇺🇳其它]
  - name: 🛑广告拦截
    type: select
    proxies: [REJECT, DIRECT]
  - name: 🍃应用净化
    type: select
    proxies: [REJECT, DIRECT]

rule-providers:
  me_direct:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/JunfenZhang1/ACL4SSR/refs/heads/me/Clash/me_direct.list
    path: ./ruleset/me_direct.list
    interval: 86400
    format: text
  me_clean:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/JunfenZhang1/ACL4SSR/refs/heads/me/Clash/me_clean.list
    path: ./ruleset/me_clean.list
    interval: 86400
    format: text
  me_select:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/JunfenZhang1/ACL4SSR/refs/heads/me/Clash/me_select.list
    path: ./ruleset/me_select.list
    interval: 86400
    format: text
  CFnat:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/CFnat.list
    path: ./ruleset/CFnat.list
    interval: 86400
    format: text
  LocalAreaNetwork:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
    interval: 86400
    format: text
  UnBan:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
    path: ./ruleset/UnBan.list
    interval: 86400
    format: text
  BanAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
    interval: 86400
    format: text
  BanProgramAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    path: ./ruleset/BanProgramAD.list
    interval: 86400
    format: text
  GoogleFCM:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
    path: ./ruleset/GoogleFCM.list
    interval: 86400
    format: text
  GoogleCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    path: ./ruleset/GoogleCN.list
    interval: 86400
    format: text
  SteamCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
    path: ./ruleset/SteamCN.list
    interval: 86400
    format: text
  Bing:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
    path: ./ruleset/Bing.list
    interval: 86400
    format: text
  OneDrive:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
    path: ./ruleset/OneDrive.list
    interval: 86400
    format: text
  Microsoft:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    path: ./ruleset/Microsoft.list
    interval: 86400
    format: text
  Apple:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    path: ./ruleset/Apple.list
    interval: 86400
    format: text
  Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
    interval: 86400
    format: text
  OpenAi:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAi.list
    interval: 86400
    format: text
  ai:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/juewuy/ShellClash/master/rules/ai.list
    path: ./ruleset/ai.list
    interval: 86400
    format: text
  Copilot:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Copilot.list
    path: ./ruleset/Copilot.list
    interval: 86400
    format: text
  GithubCopilot:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/GithubCopilot.list
    path: ./ruleset/GithubCopilot.list
    interval: 86400
    format: text
  Claude:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Claude.list
    path: ./ruleset/Claude.list
    interval: 86400
    format: text
  NetEaseMusic:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
    path: ./ruleset/NetEaseMusic.list
    interval: 86400
    format: text
  Epic:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
    path: ./ruleset/Epic.list
    interval: 86400
    format: text
  Origin:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
    path: ./ruleset/Origin.list
    interval: 86400
    format: text
  Sony:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
    path: ./ruleset/Sony.list
    interval: 86400
    format: text
  Steam:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
    path: ./ruleset/Steam.list
    interval: 86400
    format: text
  Nintendo:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
    path: ./ruleset/Nintendo.list
    interval: 86400
    format: text
  YouTube:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
    interval: 86400
    format: text
  Netflix:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
    path: ./ruleset/Netflix.list
    interval: 86400
    format: text
  Bahamut:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
    path: ./ruleset/Bahamut.list
    interval: 86400
    format: text
  BilibiliHMT:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
    path: ./ruleset/BilibiliHMT.list
    interval: 86400
    format: text
  Bilibili:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
    path: ./ruleset/Bilibili.list
    interval: 86400
    format: text
  ChinaMedia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
    path: ./ruleset/ChinaMedia.list
    interval: 86400
    format: text
  ProxyMedia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    path: ./ruleset/ProxyMedia.list
    interval: 86400
    format: text
  Emby:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Emby.list
    path: ./ruleset/Emby.list
    interval: 86400
    format: text
  ProxyGFWlist:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.list
    interval: 86400
    format: text
  proxy:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/proxy.list
    path: ./ruleset/proxy.list
    interval: 86400
    format: text
  CMBlog:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CMBlog.list
    path: ./ruleset/CMBlog.list
    interval: 86400
    format: text
  direct:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/direct.list
    path: ./ruleset/direct.list
    interval: 86400
    format: text
  ChinaDomain:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
    interval: 86400
    format: text
  ChinaCompanyIp:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
    interval: 86400
    format: text
  Download:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
    path: ./ruleset/Download.list
    interval: 86400
    format: text
  adobe:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list
    path: ./ruleset/adobe.list
    interval: 86400
    format: text
rules:
  - RULE-SET,me_direct,🎯全球直连
  - RULE-SET,me_clean,🍃ip净化
  - RULE-SET,me_select,🚀节点选择
  - RULE-SET,CFnat,🎯全球直连
  - RULE-SET,LocalAreaNetwork,🎯全球直连
  - RULE-SET,UnBan,🎯全球直连
  - RULE-SET,BanAD,🛑广告拦截
  - RULE-SET,BanProgramAD,🍃应用净化
  - RULE-SET,GoogleFCM,🚀节点选择
  - RULE-SET,GoogleCN,🎯全球直连
  - RULE-SET,SteamCN,🎯全球直连
  - RULE-SET,Bing,🚀节点选择
  - RULE-SET,OneDrive,🚀节点选择
  - RULE-SET,Microsoft,🚀节点选择
  - RULE-SET,Apple,🎯全球直连
  - RULE-SET,Telegram,🚀节点选择
  - RULE-SET,OpenAi,🤖Ai
  - RULE-SET,ai,🤖Ai
  - RULE-SET,Copilot,🤖Ai
  - RULE-SET,GithubCopilot,🤖Ai
  - RULE-SET,Claude,🤖Ai
  - RULE-SET,NetEaseMusic,🎯全球直连
  - RULE-SET,Epic,🎯全球直连
  - RULE-SET,Origin,🚀节点选择
  - RULE-SET,Sony,🚀节点选择
  - RULE-SET,Steam,🚀节点选择
  - RULE-SET,Nintendo,🚀节点选择
  - RULE-SET,YouTube,🚀节点选择
  - RULE-SET,Netflix,🚀节点选择
  - RULE-SET,Bahamut,🚀节点选择
  - RULE-SET,BilibiliHMT,📺哔哩哔哩
  - RULE-SET,Bilibili,📺哔哩哔哩
  - RULE-SET,ChinaMedia,🎯全球直连
  - RULE-SET,ProxyMedia,🚀节点选择
  - RULE-SET,Emby,🚀节点选择
  - RULE-SET,ProxyGFWlist,🚀节点选择
  - RULE-SET,proxy,🚀节点选择
  - RULE-SET,CMBlog,🚀节点选择
  - RULE-SET,direct,🎯全球直连
  - RULE-SET,ChinaDomain,🎯全球直连
  - RULE-SET,ChinaCompanyIp,🎯全球直连
  - RULE-SET,Download,🎯全球直连
  - GEOIP,CN,🎯全球直连
  - RULE-SET,adobe,🍃应用净化
  - MATCH,🐟漏网之鱼